[36m[2023-11-24 13:15:25 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:15:25 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:15:25 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:15:27 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:15:27 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:15:27 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:15:27 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:15:27 DEBUG] [caching:35][39m Cached 7 activities
[32m[2023-11-24 13:15:27 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:15:27 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:15:27 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:15:27 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:15:27 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:15:27 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:15:27 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:15:27 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:15:27 DEBUG] [caching:35][39m Cached 7 activities
[36m[2023-11-24 13:15:27 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:15:27 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:15:27 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:15:27 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:15:27 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:15:27 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:15:27 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:15:27 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:15:27 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:15:27 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:15:27 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:15:27 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:15:27 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:15:27 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:15:27 INFO] [activity:215][39m Probe: the-astre-service-must-be-running
[36m[2023-11-24 13:15:27 DEBUG] [python:33][39m Activity 'the-astre-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:15:27 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-24 13:15:27 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:15:27 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:15:27 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-24 13:15:27 CRITICAL] [run:579][39m Steady state probe 'the-astre-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-24 13:15:27 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:15:27 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:15:27 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:15:27 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:15:27 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:15:27 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[33m[2023-11-24 13:15:28 WARNING] [process:70][39m This process returned a non-zero exit code. This may indicate some error and not what you expected. Please have a look at the logs.
[36m[2023-11-24 13:15:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:15:28 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-11-24 13:15:28 DEBUG] [activity:237][39m   => succeeded with '{'status': 1, 'stdout': '', 'stderr': "/usr/bin/cp: cannot stat 'valid-cert.pem': No such file or directory\n"}'
[36m[2023-11-24 13:15:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:15:28 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:15:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:15:28 INFO] [activity:215][39m Action: restart-astre-service-to-pick-up-certificate
[36m[2023-11-24 13:15:28 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F astre.pid
[36m[2023-11-24 13:15:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:15:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:15:28 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:15:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:15:28 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:15:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:15:28 INFO] [activity:215][39m Action: restart-sunset-service-to-pick-up-certificate
[36m[2023-11-24 13:15:28 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F sunset.pid
[36m[2023-11-24 13:15:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:15:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:15:28 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[32m[2023-11-24 13:15:28 INFO] [activity:257][39m Pausing after activity for 1s...
[36m[2023-11-24 13:15:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:15:29 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:15:29 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:15:29 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:15:29 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:15:29 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:22:11 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:22:11 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:22:11 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:22:12 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:22:12 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:22:12 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:22:12 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:22:12 DEBUG] [caching:35][39m Cached 7 activities
[32m[2023-11-24 13:22:12 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:22:12 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:22:12 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:22:12 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:22:12 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:22:12 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:22:12 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:22:12 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:22:12 DEBUG] [caching:35][39m Cached 7 activities
[36m[2023-11-24 13:22:12 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:22:12 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:22:12 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:22:12 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:22:12 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:22:12 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:22:12 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:22:12 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:22:12 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:22:12 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:22:12 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:22:12 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:22:12 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:22:12 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:22:12 INFO] [activity:215][39m Probe: the-astre-service-must-be-running
[36m[2023-11-24 13:22:12 DEBUG] [python:33][39m Activity 'the-astre-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:22:12 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-24 13:22:12 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:22:12 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:22:12 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-24 13:22:12 CRITICAL] [run:579][39m Steady state probe 'the-astre-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-24 13:22:12 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:22:12 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:22:12 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:22:12 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:22:12 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:22:12 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[33m[2023-11-24 13:22:13 WARNING] [process:70][39m This process returned a non-zero exit code. This may indicate some error and not what you expected. Please have a look at the logs.
[36m[2023-11-24 13:22:13 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:22:13 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-11-24 13:22:13 DEBUG] [activity:237][39m   => succeeded with '{'status': 1, 'stdout': '', 'stderr': "/usr/bin/cp: cannot stat 'valid-cert.pem': No such file or directory\n"}'
[36m[2023-11-24 13:22:13 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:22:13 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:22:13 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:22:13 INFO] [activity:215][39m Action: restart-astre-service-to-pick-up-certificate
[36m[2023-11-24 13:22:13 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F astre.pid
[36m[2023-11-24 13:22:13 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:22:13 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:22:13 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:22:13 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:22:13 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:22:13 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:22:13 INFO] [activity:215][39m Action: restart-sunset-service-to-pick-up-certificate
[36m[2023-11-24 13:22:13 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F sunset.pid
[36m[2023-11-24 13:22:13 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:22:13 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:22:13 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[32m[2023-11-24 13:22:13 INFO] [activity:257][39m Pausing after activity for 1s...
[36m[2023-11-24 13:22:14 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:22:14 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:22:14 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:22:14 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:22:14 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:22:14 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:23:37 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:23:37 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:23:37 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:23:39 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:23:39 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:23:39 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:23:39 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:23:39 DEBUG] [caching:35][39m Cached 7 activities
[32m[2023-11-24 13:23:39 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:23:39 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:23:39 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:23:39 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:23:39 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:23:39 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:23:39 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:23:39 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:23:39 DEBUG] [caching:35][39m Cached 7 activities
[36m[2023-11-24 13:23:39 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:23:39 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:23:39 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:23:39 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:23:39 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:23:39 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:23:39 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:23:39 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:23:39 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:23:39 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:23:39 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:23:39 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:23:39 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:23:39 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:23:39 INFO] [activity:215][39m Probe: the-astre-service-must-be-running
[36m[2023-11-24 13:23:39 DEBUG] [python:33][39m Activity 'the-astre-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:23:39 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-24 13:23:39 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:23:39 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:23:39 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-24 13:23:39 CRITICAL] [run:579][39m Steady state probe 'the-astre-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-24 13:23:39 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:23:39 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:23:39 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:23:39 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:23:39 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:23:39 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[33m[2023-11-24 13:23:39 WARNING] [process:70][39m This process returned a non-zero exit code. This may indicate some error and not what you expected. Please have a look at the logs.
[36m[2023-11-24 13:23:39 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:23:39 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-11-24 13:23:39 DEBUG] [activity:237][39m   => succeeded with '{'status': 1, 'stdout': '', 'stderr': "/usr/bin/cp: cannot stat 'valid-cert.pem': No such file or directory\n"}'
[36m[2023-11-24 13:23:39 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:23:39 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:23:39 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:23:39 INFO] [activity:215][39m Action: restart-astre-service-to-pick-up-certificate
[36m[2023-11-24 13:23:39 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F astre.pid
[36m[2023-11-24 13:23:39 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:23:39 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:23:39 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:23:39 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:23:39 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:23:39 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:23:39 INFO] [activity:215][39m Action: restart-sunset-service-to-pick-up-certificate
[36m[2023-11-24 13:23:39 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F sunset.pid
[36m[2023-11-24 13:23:39 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:23:39 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:23:39 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[32m[2023-11-24 13:23:39 INFO] [activity:257][39m Pausing after activity for 1s...
[36m[2023-11-24 13:23:40 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:23:40 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:23:40 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:23:40 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:23:40 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:23:40 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:33:26 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:33:26 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:33:26 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:33:27 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:33:27 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:33:27 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:33:27 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:33:27 DEBUG] [caching:35][39m Cached 7 activities
[32m[2023-11-24 13:33:27 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:33:27 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:33:27 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:33:27 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:33:27 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:33:27 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:33:27 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:33:27 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:33:27 DEBUG] [caching:35][39m Cached 7 activities
[36m[2023-11-24 13:33:27 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:33:27 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:33:27 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:33:27 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:33:27 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:33:27 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:33:27 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:33:27 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:33:27 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:33:27 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:33:27 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:33:27 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:33:27 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:33:27 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:33:27 INFO] [activity:215][39m Probe: the-astre-service-must-be-running
[36m[2023-11-24 13:33:27 DEBUG] [python:33][39m Activity 'the-astre-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:33:27 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-24 13:33:27 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:33:27 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:33:27 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-24 13:33:27 CRITICAL] [run:579][39m Steady state probe 'the-astre-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-24 13:33:27 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:33:27 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:33:27 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:33:27 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:33:27 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:33:27 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[36m[2023-11-24 13:33:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:33:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:33:28 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:33:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:33:28 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:33:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:33:28 INFO] [activity:215][39m Action: restart-astre-service-to-pick-up-certificate
[36m[2023-11-24 13:33:28 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F astre.pid
[36m[2023-11-24 13:33:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:33:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:33:28 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:33:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:33:28 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:33:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:33:28 INFO] [activity:215][39m Action: restart-sunset-service-to-pick-up-certificate
[36m[2023-11-24 13:33:28 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F sunset.pid
[36m[2023-11-24 13:33:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:33:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:33:28 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[32m[2023-11-24 13:33:28 INFO] [activity:257][39m Pausing after activity for 1s...
[36m[2023-11-24 13:33:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:33:29 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:33:29 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:33:29 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:33:29 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:33:29 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:34:28 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:34:28 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:34:28 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:34:29 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:34:29 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:34:29 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:34:29 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:34:29 DEBUG] [caching:35][39m Cached 7 activities
[32m[2023-11-24 13:34:29 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:34:29 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:34:29 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:34:29 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:34:29 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:34:29 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:34:29 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:34:29 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:34:29 DEBUG] [caching:35][39m Cached 7 activities
[36m[2023-11-24 13:34:29 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:34:29 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:34:29 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:34:29 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:34:29 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:34:29 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:34:29 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:34:29 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:34:29 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:34:29 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:34:29 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:34:29 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:34:29 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:34:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:34:29 INFO] [activity:215][39m Probe: the-astre-service-must-be-running
[36m[2023-11-24 13:34:29 DEBUG] [python:33][39m Activity 'the-astre-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:34:29 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-24 13:34:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:34:29 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:34:29 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-24 13:34:29 CRITICAL] [run:579][39m Steady state probe 'the-astre-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-24 13:34:29 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:34:29 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:34:29 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:34:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:34:29 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:34:29 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[36m[2023-11-24 13:34:29 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:34:29 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:34:29 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:34:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:34:29 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:34:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:34:29 INFO] [activity:215][39m Action: restart-astre-service-to-pick-up-certificate
[36m[2023-11-24 13:34:29 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F astre.pid
[36m[2023-11-24 13:34:29 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:34:29 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:34:29 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:34:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:34:29 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:34:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:34:29 INFO] [activity:215][39m Action: restart-sunset-service-to-pick-up-certificate
[36m[2023-11-24 13:34:29 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F sunset.pid
[36m[2023-11-24 13:34:30 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:34:30 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:34:30 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[32m[2023-11-24 13:34:30 INFO] [activity:257][39m Pausing after activity for 1s...
[36m[2023-11-24 13:34:31 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:34:31 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:34:31 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:34:31 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:34:31 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:34:31 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:35:35 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:35:35 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:35:35 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:35:36 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:35:36 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:35:36 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:35:36 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:35:36 DEBUG] [caching:35][39m Cached 7 activities
[32m[2023-11-24 13:35:36 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:35:36 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:35:36 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:35:36 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:35:36 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:35:36 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:35:36 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:35:36 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:35:36 DEBUG] [caching:35][39m Cached 7 activities
[36m[2023-11-24 13:35:36 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:35:36 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:35:36 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:35:36 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:35:36 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:35:36 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:35:36 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:35:36 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:35:36 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:35:36 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:35:36 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:35:36 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:35:36 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:35:36 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:35:36 INFO] [activity:215][39m Probe: the-astre-service-must-be-running
[36m[2023-11-24 13:35:36 DEBUG] [python:33][39m Activity 'the-astre-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:35:36 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-24 13:35:36 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:35:36 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:35:36 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-24 13:35:36 CRITICAL] [run:579][39m Steady state probe 'the-astre-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-24 13:35:36 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:35:36 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:35:36 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:35:36 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:35:36 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:35:36 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[36m[2023-11-24 13:35:36 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:35:36 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:35:36 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:35:36 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:35:36 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:35:36 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:35:36 INFO] [activity:215][39m Action: restart-astre-service-to-pick-up-certificate
[36m[2023-11-24 13:35:36 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F astre.pid
[36m[2023-11-24 13:35:36 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:35:36 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:35:36 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:35:36 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:35:36 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:35:36 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:35:36 INFO] [activity:215][39m Action: restart-sunset-service-to-pick-up-certificate
[36m[2023-11-24 13:35:36 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F sunset.pid
[36m[2023-11-24 13:35:37 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:35:37 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:35:37 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[32m[2023-11-24 13:35:37 INFO] [activity:257][39m Pausing after activity for 1s...
[36m[2023-11-24 13:35:38 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:35:38 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:35:38 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:35:38 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:35:38 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:35:38 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:38:05 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:38:05 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:38:05 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:38:06 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:38:06 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:38:06 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:38:06 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:38:06 DEBUG] [caching:35][39m Cached 5 activities
[32m[2023-11-24 13:38:06 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:38:06 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:38:06 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:38:06 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:38:06 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:38:06 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:38:06 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:38:06 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:38:06 DEBUG] [caching:35][39m Cached 5 activities
[36m[2023-11-24 13:38:06 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:38:06 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:38:06 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:38:06 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:38:06 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:38:06 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:38:06 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:38:06 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:38:06 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:38:06 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:38:06 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:38:06 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:38:06 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:38:06 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:06 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:38:06 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:38:06 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-24 13:38:06 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:38:06 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:38:06 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:06 INFO] [activity:215][39m Probe: we-can-request-bookmark
[36m[2023-11-24 13:38:08 DEBUG] [activity:237][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Server': 'CherryPy/18.8.0', 'Date': 'Fri, 24 Nov 2023 12:38:08 GMT', 'Content-Length': '45'}, 'body': {'operation': 'request', 'result': 'success'}}'
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:38:08 DEBUG] [hypothesis:228][39m allowed tolerance is 200
[32m[2023-11-24 13:38:08 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-24 13:38:08 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:08 INFO] [activity:215][39m Action: swap-to-expired-cert
[36m[2023-11-24 13:38:08 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE expired-cert.pem cert.pem
[36m[2023-11-24 13:38:08 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:38:08 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:38:08 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:08 INFO] [activity:215][39m Probe: read-tls-cert-expiry-date
[36m[2023-11-24 13:38:08 DEBUG] [process:52][39m Running: C:\cygwin64\bin\openssl.EXE x509 -enddate -noout -in cert.pem
[36m[2023-11-24 13:38:08 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-11-24 13:38:08 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:38:08 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': 'notAfter=May  5 15:00:00 2018 GMT\n', 'stderr': ''}'
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:08 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:38:08 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:38:08 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:38:08 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:38:08 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-24 13:38:08 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-11-24 13:38:08 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:08 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:38:08 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:38:08 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:38:08 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:38:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:08 INFO] [activity:215][39m Probe: we-can-request-bookmark
[36m[2023-11-24 13:38:10 DEBUG] [activity:237][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Server': 'CherryPy/18.8.0', 'Date': 'Fri, 24 Nov 2023 12:38:10 GMT', 'Content-Length': '45'}, 'body': {'operation': 'request', 'result': 'success'}}'
[36m[2023-11-24 13:38:10 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:38:10 DEBUG] [hypothesis:228][39m allowed tolerance is 200
[32m[2023-11-24 13:38:10 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-24 13:38:10 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-24 13:38:10 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:38:10 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:38:10 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:38:10 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:10 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:38:10 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[36m[2023-11-24 13:38:11 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:38:11 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:38:11 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:38:11 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:11 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:38:11 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:11 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:38:11 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:38:11 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:38:11 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:38:11 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:38:11 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:38:11 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:38:11 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:38:11 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:38:11 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:38:11 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:38:36 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:38:36 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:38:36 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:38:37 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:38:37 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:38:37 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:38:37 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:38:37 DEBUG] [caching:35][39m Cached 5 activities
[32m[2023-11-24 13:38:37 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:38:37 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:38:37 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:38:37 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:38:38 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:38:38 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:38:38 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:38:38 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:38:38 DEBUG] [caching:35][39m Cached 5 activities
[36m[2023-11-24 13:38:38 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:38:38 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:38:38 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:38:38 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:38:38 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:38:38 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:38:38 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:38:38 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:38:38 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:38:38 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:38:38 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:38:38 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:38:38 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:38:38 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:38 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:38:38 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:38:38 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-24 13:38:38 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:38:38 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:38:38 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-24 13:38:38 CRITICAL] [run:579][39m Steady state probe 'the-bookmark-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-24 13:38:38 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:38:38 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:38:38 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:38:38 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:38 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:38:38 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[36m[2023-11-24 13:38:38 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:38:38 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:38:38 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:38:38 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:38 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:38:38 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:38:38 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:38:38 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:38:38 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:38:38 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:38:38 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:38:38 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:38:38 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:38:38 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:38:38 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:38:38 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:38:38 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:41:46 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:41:46 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:41:46 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:41:47 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:41:47 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:41:47 DEBUG] [caching:35][39m Cached 5 activities
[32m[2023-11-24 13:41:47 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:41:47 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:41:47 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:41:47 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:41:47 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:41:47 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:41:47 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:41:47 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:41:47 DEBUG] [caching:35][39m Cached 5 activities
[36m[2023-11-24 13:41:47 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:41:47 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:41:47 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:41:47 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:41:47 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:41:47 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:41:47 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:41:47 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:41:47 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:41:47 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:41:47 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:41:47 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:41:47 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:41:47 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:41:47 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-24 13:41:47 CRITICAL] [run:579][39m Steady state probe 'the-bookmark-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-24 13:41:47 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:41:47 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:41:47 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:41:47 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[33m[2023-11-24 13:41:47 WARNING] [process:70][39m This process returned a non-zero exit code. This may indicate some error and not what you expected. Please have a look at the logs.
[36m[2023-11-24 13:41:47 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:41:47 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-11-24 13:41:47 DEBUG] [activity:237][39m   => succeeded with '{'status': 1, 'stdout': '', 'stderr': "/usr/bin/cp: cannot stat 'valid-cert.pem': No such file or directory\n"}'
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:41:47 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:41:47 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:41:47 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:41:47 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:41:47 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:41:47 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:41:47 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:41:47 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:41:47 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:41:47 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:42:27 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:42:27 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:42:27 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:42:28 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:42:28 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:42:28 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:42:28 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:42:28 DEBUG] [caching:35][39m Cached 5 activities
[32m[2023-11-24 13:42:28 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:42:28 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:42:28 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:42:28 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:42:28 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:42:28 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:42:28 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:42:28 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:42:28 DEBUG] [caching:35][39m Cached 5 activities
[36m[2023-11-24 13:42:28 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:42:28 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:42:28 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:42:28 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:42:28 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:42:28 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:42:28 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:42:28 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:42:28 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:42:28 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:42:28 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:42:28 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:42:28 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:42:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:42:28 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:42:28 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:42:28 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-24 13:42:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:42:28 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:42:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:42:28 INFO] [activity:215][39m Probe: we-can-request-bookmark
[36m[2023-11-24 13:42:30 DEBUG] [activity:237][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Server': 'CherryPy/18.8.0', 'Date': 'Fri, 24 Nov 2023 12:42:30 GMT', 'Content-Length': '45'}, 'body': {'operation': 'request', 'result': 'success'}}'
[36m[2023-11-24 13:42:30 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:42:30 DEBUG] [hypothesis:228][39m allowed tolerance is 200
[32m[2023-11-24 13:42:30 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-24 13:42:30 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-24 13:42:30 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-11-24 13:42:30 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-24 13:42:30 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:42:30 INFO] [activity:215][39m Action: swap-to-expired-cert
[36m[2023-11-24 13:42:30 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE expired-cert.pem cert.pem
[36m[2023-11-24 13:42:31 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:42:31 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:42:31 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:42:31 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:42:31 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:42:31 INFO] [activity:215][39m Probe: read-tls-cert-expiry-date
[36m[2023-11-24 13:42:31 DEBUG] [process:52][39m Running: C:\cygwin64\bin\openssl.EXE x509 -enddate -noout -in cert.pem
[36m[2023-11-24 13:42:31 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-11-24 13:42:31 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:42:31 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': 'notAfter=May  5 15:00:00 2018 GMT\n', 'stderr': ''}'
[36m[2023-11-24 13:42:31 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:42:31 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:42:31 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:42:31 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:42:31 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:42:31 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:42:31 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:42:31 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:42:31 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-24 13:42:31 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-11-24 13:42:31 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:42:31 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:42:31 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:42:31 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:42:31 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:42:31 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-24 13:42:31 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:42:31 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:42:31 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:42:31 INFO] [activity:215][39m Probe: we-can-request-bookmark
[36m[2023-11-24 13:42:33 DEBUG] [activity:237][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Server': 'CherryPy/18.8.0', 'Date': 'Fri, 24 Nov 2023 12:42:33 GMT', 'Content-Length': '45'}, 'body': {'operation': 'request', 'result': 'success'}}'
[36m[2023-11-24 13:42:33 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:42:33 DEBUG] [hypothesis:228][39m allowed tolerance is 200
[32m[2023-11-24 13:42:33 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-24 13:42:33 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-24 13:42:33 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:42:33 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:42:33 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:42:33 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:42:33 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:42:33 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[33m[2023-11-24 13:42:33 WARNING] [process:70][39m This process returned a non-zero exit code. This may indicate some error and not what you expected. Please have a look at the logs.
[36m[2023-11-24 13:42:33 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:42:33 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-11-24 13:42:33 DEBUG] [activity:237][39m   => succeeded with '{'status': 1, 'stdout': '', 'stderr': "/usr/bin/cp: cannot stat 'valid-cert.pem': No such file or directory\n"}'
[36m[2023-11-24 13:42:33 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:42:33 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:42:33 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:42:33 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:42:33 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:42:33 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:42:33 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:42:33 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:42:33 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:42:33 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:42:33 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:42:33 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:42:33 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:42:33 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:43:32 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:43:32 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:43:32 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:43:33 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:43:33 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:43:33 DEBUG] [caching:35][39m Cached 5 activities
[32m[2023-11-24 13:43:33 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:43:33 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:43:33 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:43:33 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:43:33 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:43:33 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:43:33 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:43:33 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:43:33 DEBUG] [caching:35][39m Cached 5 activities
[36m[2023-11-24 13:43:33 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:43:33 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:43:33 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:43:33 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:43:33 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:43:33 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:43:33 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:43:33 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:43:33 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:43:33 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:43:33 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:43:33 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:43:33 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:43:33 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:43:33 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-24 13:43:33 CRITICAL] [run:579][39m Steady state probe 'the-bookmark-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-24 13:43:33 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:43:33 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:43:33 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:43:33 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[36m[2023-11-24 13:43:33 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:43:33 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:43:33 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:43:33 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:43:33 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:43:33 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:43:33 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:43:33 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:43:33 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:43:33 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:43:33 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:43:33 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:43:33 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:43:40 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:43:40 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:43:40 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:43:41 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:43:41 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:43:41 DEBUG] [caching:35][39m Cached 5 activities
[32m[2023-11-24 13:43:41 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:43:41 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:43:41 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:43:41 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:43:41 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:43:41 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:43:41 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:43:41 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:43:41 DEBUG] [caching:35][39m Cached 5 activities
[36m[2023-11-24 13:43:41 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:43:41 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:43:41 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:43:41 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:43:41 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:43:41 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:43:41 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:43:41 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:43:41 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:43:41 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:43:41 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:43:41 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:43:41 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:43:41 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:43:41 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-24 13:43:41 CRITICAL] [run:579][39m Steady state probe 'the-bookmark-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-24 13:43:41 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:43:41 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:43:41 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:43:41 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[36m[2023-11-24 13:43:41 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:43:41 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:43:41 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:43:41 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:43:41 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:43:41 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:43:41 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:43:41 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:43:41 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:43:41 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:43:41 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:43:41 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:43:41 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:43:58 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:43:58 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:43:58 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:43:58 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:43:58 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:43:58 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:43:58 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:43:58 DEBUG] [caching:35][39m Cached 5 activities
[32m[2023-11-24 13:43:58 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:43:58 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:43:58 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:43:58 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:43:58 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:43:58 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:43:58 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:43:58 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:43:58 DEBUG] [caching:35][39m Cached 5 activities
[36m[2023-11-24 13:43:58 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:43:58 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:43:58 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:43:58 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:43:58 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:43:58 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:43:58 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:43:58 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:43:58 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:43:58 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:43:58 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:43:58 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:43:58 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:43:58 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:43:58 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:43:58 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:43:58 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-24 13:43:58 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:43:58 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:43:58 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:43:58 INFO] [activity:215][39m Probe: we-can-request-bookmark
[36m[2023-11-24 13:44:00 DEBUG] [activity:237][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Server': 'CherryPy/18.8.0', 'Date': 'Fri, 24 Nov 2023 12:44:00 GMT', 'Content-Length': '45'}, 'body': {'operation': 'request', 'result': 'success'}}'
[36m[2023-11-24 13:44:00 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:44:00 DEBUG] [hypothesis:228][39m allowed tolerance is 200
[32m[2023-11-24 13:44:00 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-24 13:44:00 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-24 13:44:00 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-11-24 13:44:00 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-24 13:44:00 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:44:00 INFO] [activity:215][39m Action: swap-to-expired-cert
[36m[2023-11-24 13:44:00 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE expired-cert.pem cert.pem
[36m[2023-11-24 13:44:01 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:44:01 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:44:01 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:44:01 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:44:01 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:44:01 INFO] [activity:215][39m Probe: read-tls-cert-expiry-date
[36m[2023-11-24 13:44:01 DEBUG] [process:52][39m Running: C:\cygwin64\bin\openssl.EXE x509 -enddate -noout -in cert.pem
[36m[2023-11-24 13:44:01 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-11-24 13:44:01 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:44:01 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': 'notAfter=May  5 15:00:00 2018 GMT\n', 'stderr': ''}'
[36m[2023-11-24 13:44:01 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:44:01 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:44:01 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:44:01 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:44:01 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:44:01 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:44:01 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:44:01 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:44:01 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-24 13:44:01 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-11-24 13:44:01 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:44:01 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:44:01 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:44:01 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:44:01 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:44:01 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-24 13:44:01 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:44:01 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:44:01 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:44:01 INFO] [activity:215][39m Probe: we-can-request-bookmark
[36m[2023-11-24 13:44:03 DEBUG] [activity:237][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Server': 'CherryPy/18.8.0', 'Date': 'Fri, 24 Nov 2023 12:44:03 GMT', 'Content-Length': '45'}, 'body': {'operation': 'request', 'result': 'success'}}'
[36m[2023-11-24 13:44:03 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:44:03 DEBUG] [hypothesis:228][39m allowed tolerance is 200
[32m[2023-11-24 13:44:03 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-24 13:44:03 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-24 13:44:03 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:44:03 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:44:03 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:44:03 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:44:03 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:44:03 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[36m[2023-11-24 13:44:03 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:44:03 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:44:03 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:44:03 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:44:03 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:44:03 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:44:03 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:44:03 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:44:03 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:44:03 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:44:03 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:44:03 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:44:03 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:44:03 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:44:03 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:44:03 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:44:03 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:49:29 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:49:29 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:49:29 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:49:30 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:49:30 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:49:30 DEBUG] [caching:35][39m Cached 5 activities
[32m[2023-11-24 13:49:30 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:49:30 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:49:30 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:49:30 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:49:30 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:49:30 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:49:30 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:49:30 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:49:30 DEBUG] [caching:35][39m Cached 5 activities
[36m[2023-11-24 13:49:30 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:49:30 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:49:30 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:49:30 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:49:30 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:49:30 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:49:30 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:49:30 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:49:30 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:49:30 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:49:30 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:49:30 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:49:30 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:49:30 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:49:30 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-24 13:49:30 CRITICAL] [run:579][39m Steady state probe 'the-bookmark-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-24 13:49:30 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:49:30 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:49:30 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:49:30 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[36m[2023-11-24 13:49:30 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:49:30 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:49:30 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:49:30 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:49:30 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:49:30 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:49:30 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:49:30 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:49:30 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:49:30 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:49:30 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:49:30 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:49:30 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:50:22 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:50:22 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:50:22 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:50:23 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:50:23 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:50:23 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:50:23 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:50:23 DEBUG] [caching:35][39m Cached 5 activities
[32m[2023-11-24 13:50:23 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:50:23 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:50:23 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:50:23 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:50:23 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:50:23 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:50:23 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:50:23 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:50:23 DEBUG] [caching:35][39m Cached 5 activities
[36m[2023-11-24 13:50:23 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:50:23 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:50:23 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:50:23 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:50:23 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:50:23 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:50:23 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:50:23 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:50:23 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:50:23 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:50:23 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:50:23 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:50:23 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:50:23 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:23 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:50:23 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:50:23 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-24 13:50:23 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:50:23 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:50:23 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:23 INFO] [activity:215][39m Probe: we-can-request-bookmark
[36m[2023-11-24 13:50:25 DEBUG] [activity:237][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Server': 'CherryPy/18.8.0', 'Date': 'Fri, 24 Nov 2023 12:50:25 GMT', 'Content-Length': '45'}, 'body': {'operation': 'request', 'result': 'success'}}'
[36m[2023-11-24 13:50:25 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:50:25 DEBUG] [hypothesis:228][39m allowed tolerance is 200
[32m[2023-11-24 13:50:25 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-24 13:50:25 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-24 13:50:25 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-11-24 13:50:25 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-24 13:50:25 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:25 INFO] [activity:215][39m Action: swap-to-expired-cert
[36m[2023-11-24 13:50:25 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE expired-cert.pem cert.pem
[36m[2023-11-24 13:50:26 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:50:26 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:50:26 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:50:26 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:50:26 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:26 INFO] [activity:215][39m Probe: read-tls-cert-expiry-date
[36m[2023-11-24 13:50:26 DEBUG] [process:52][39m Running: C:\cygwin64\bin\openssl.EXE x509 -enddate -noout -in cert.pem
[36m[2023-11-24 13:50:26 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-11-24 13:50:26 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:50:26 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': 'notAfter=May  5 15:00:00 2018 GMT\n', 'stderr': ''}'
[36m[2023-11-24 13:50:26 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:50:26 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:26 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:50:26 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:50:26 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:50:26 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:50:26 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:50:26 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:50:26 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-24 13:50:26 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-11-24 13:50:26 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:50:26 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:50:26 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:26 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:50:26 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:50:26 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-24 13:50:26 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:50:26 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:50:26 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:26 INFO] [activity:215][39m Probe: we-can-request-bookmark
[36m[2023-11-24 13:50:28 DEBUG] [activity:237][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Server': 'CherryPy/18.8.0', 'Date': 'Fri, 24 Nov 2023 12:50:28 GMT', 'Content-Length': '45'}, 'body': {'operation': 'request', 'result': 'success'}}'
[36m[2023-11-24 13:50:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:50:28 DEBUG] [hypothesis:228][39m allowed tolerance is 200
[32m[2023-11-24 13:50:28 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-24 13:50:28 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-24 13:50:28 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:50:28 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:50:28 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:50:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:28 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:50:28 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[36m[2023-11-24 13:50:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:50:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:50:28 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:50:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:28 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:50:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:28 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:50:28 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:50:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:50:28 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:50:28 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:50:28 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:50:28 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:50:28 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:50:28 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:50:28 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:50:28 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:50:48 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:50:48 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:50:48 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:50:49 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:50:49 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:50:49 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:50:49 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:50:49 DEBUG] [caching:35][39m Cached 5 activities
[32m[2023-11-24 13:50:49 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:50:49 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:50:49 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:50:49 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:50:49 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:50:49 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:50:49 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:50:49 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:50:49 DEBUG] [caching:35][39m Cached 5 activities
[36m[2023-11-24 13:50:49 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:50:49 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:50:49 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:50:49 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:50:49 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:50:49 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:50:49 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:50:49 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:50:49 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:50:49 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:50:49 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:50:49 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:50:49 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:50:49 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:49 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:50:49 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:50:49 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-24 13:50:49 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:50:49 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:50:49 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-24 13:50:49 CRITICAL] [run:579][39m Steady state probe 'the-bookmark-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-24 13:50:49 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:50:49 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:50:49 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:50:49 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:49 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:50:49 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[36m[2023-11-24 13:50:50 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:50:50 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:50:50 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:50:50 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:50 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:50:50 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:50:50 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:50:50 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:50:50 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:50:50 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:50:50 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:50:50 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:50:50 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:50:50 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:50:50 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:50:50 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:50:50 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:55:46 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:55:46 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:55:46 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:55:47 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:55:47 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:55:47 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:55:47 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:55:47 DEBUG] [caching:35][39m Cached 5 activities
[32m[2023-11-24 13:55:47 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:55:47 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:55:47 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:55:47 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:55:47 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:55:47 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:55:47 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:55:47 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:55:47 DEBUG] [caching:35][39m Cached 5 activities
[36m[2023-11-24 13:55:47 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:55:47 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:55:47 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:55:47 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:55:47 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:55:47 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:55:47 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:55:47 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:55:47 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:55:47 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:55:47 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:55:47 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:55:47 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:55:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:55:47 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:55:47 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:55:47 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-24 13:55:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:55:47 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:55:47 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-24 13:55:47 CRITICAL] [run:579][39m Steady state probe 'the-bookmark-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-24 13:55:47 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:55:47 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:55:47 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:55:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:55:47 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:55:47 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[36m[2023-11-24 13:55:48 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:55:48 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:55:48 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:55:48 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:55:48 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:55:48 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:55:48 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:55:48 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:55:48 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:55:48 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:55:48 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:55:48 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:55:48 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:55:48 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:55:48 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:55:48 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:55:48 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:56:14 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-24 13:56:14 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-24 13:56:14 DEBUG] [cli:119][39m Using settings file 'C:\Users\angel\.chaostoolkit\settings.yaml'
[36m[2023-11-24 13:56:15 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\angel\.chaostoolkit\settings.yaml'.
[36m[2023-11-24 13:56:15 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:56:15 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-24 13:56:15 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:56:15 DEBUG] [caching:35][39m Cached 5 activities
[32m[2023-11-24 13:56:15 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-24 13:56:15 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:56:15 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:56:15 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-24 13:56:15 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-24 13:56:15 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-24 13:56:15 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-24 13:56:15 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-24 13:56:15 DEBUG] [caching:35][39m Cached 5 activities
[36m[2023-11-24 13:56:15 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-24 13:56:15 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-24 13:56:15 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-24 13:56:15 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-24 13:56:15 DEBUG] [exit:89][39m System 'Windows-10-10.0.19041-SP0' does not expose SIGUSR signals
[32m[2023-11-24 13:56:15 INFO] [run:369][39m Running experiment: What is the impact of an expired certificate on our application chain?
[36m[2023-11-24 13:56:15 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-24 13:56:15 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-24 13:56:15 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-24 13:56:15 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:56:15 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-24 13:56:15 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:56:15 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:56:15 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:56:15 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:56:15 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:56:15 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-24 13:56:15 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:56:15 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:56:15 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:56:15 INFO] [activity:215][39m Probe: we-can-request-bookmark
[36m[2023-11-24 13:56:18 DEBUG] [activity:237][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Server': 'CherryPy/18.8.0', 'Date': 'Fri, 24 Nov 2023 12:56:18 GMT', 'Content-Length': '45'}, 'body': {'operation': 'request', 'result': 'success'}}'
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:56:18 DEBUG] [hypothesis:228][39m allowed tolerance is 200
[32m[2023-11-24 13:56:18 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-24 13:56:18 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:56:18 INFO] [activity:215][39m Action: swap-to-expired-cert
[36m[2023-11-24 13:56:18 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE expired-cert.pem cert.pem
[36m[2023-11-24 13:56:18 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:56:18 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:56:18 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:56:18 INFO] [activity:215][39m Probe: read-tls-cert-expiry-date
[36m[2023-11-24 13:56:18 DEBUG] [process:52][39m Running: C:\cygwin64\bin\openssl.EXE x509 -enddate -noout -in cert.pem
[36m[2023-11-24 13:56:18 DEBUG] [__init__:149][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2023-11-24 13:56:18 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:56:18 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': 'notAfter=May  5 15:00:00 2018 GMT\n', 'stderr': ''}'
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:56:18 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:56:18 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:56:18 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:56:18 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:56:18 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-24 13:56:18 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-11-24 13:56:18 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:56:18 INFO] [activity:215][39m Probe: the-bookmark-service-must-be-running
[36m[2023-11-24 13:56:18 DEBUG] [python:33][39m Activity 'the-bookmark-service-must-be-running' loaded from 'c:\program files\python38\lib\genericpath.py'
[36m[2023-11-24 13:56:18 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:56:18 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-24 13:56:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:56:18 INFO] [activity:215][39m Probe: we-can-request-bookmark
[36m[2023-11-24 13:56:20 DEBUG] [activity:237][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Server': 'CherryPy/18.8.0', 'Date': 'Fri, 24 Nov 2023 12:56:20 GMT', 'Content-Length': '45'}, 'body': {'operation': 'request', 'result': 'success'}}'
[36m[2023-11-24 13:56:20 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:56:20 DEBUG] [hypothesis:228][39m allowed tolerance is 200
[32m[2023-11-24 13:56:20 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-24 13:56:20 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-24 13:56:20 INFO] [run:966][39m Let's rollback...
[36m[2023-11-24 13:56:20 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:56:20 INFO] [rollback:35][39m Rollback: swap-to-valid-cert
[36m[2023-11-24 13:56:20 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:56:20 INFO] [activity:215][39m Action: swap-to-valid-cert
[36m[2023-11-24 13:56:20 DEBUG] [process:52][39m Running: C:\cygwin64\bin\cp.EXE valid-cert.pem cert.pem
[36m[2023-11-24 13:56:20 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:56:20 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:56:20 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:56:20 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:56:20 INFO] [rollback:35][39m Rollback: None
[36m[2023-11-24 13:56:20 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-24 13:56:20 INFO] [activity:215][39m Action: restart-bookmark-service-to-pick-up-certificate
[36m[2023-11-24 13:56:20 DEBUG] [process:52][39m Running: C:\Users\angel\Desktop\skw\chaos\pkill\pkill.PY --echo -HUP -F bookmark.pid
[36m[2023-11-24 13:56:20 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:56:20 DEBUG] [__init__:149][39m Data encoding detected as 'utf-8' with a confidence of 1.0
[36m[2023-11-24 13:56:20 DEBUG] [activity:237][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[36m[2023-11-24 13:56:20 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-24 13:56:20 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-24 13:56:20 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-24 13:56:20 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-24 13:56:20 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-24 13:56:20 DEBUG] [caching:42][39m Clearing activities cache
